### ISSUE TITLE
[FEAT] Landing Page Development Using Wordpress + Divi Builder

### ISSUE THREAD

**Issue by Aries1711** [coinresearch-ai/product-management#1]
### Overview

Say hooray, our design for v2 landing pages is already done 🚀 , now it's the time for the Frontend Team to take the estafet point by developing the v2 landing page using WordPress and Divi builder and replacing our old v1 landing page website design.

### Platform Affected

1. Web Browser

### Definition of done

- [x] slicing UI design frontpage on responsive layout and platform devices.
- [ ] Slicing UI design about page on responsive layout and platform devices.
- [ ] Slicing UI design waitlist page on responsive layout and platform devices.
- [ ] Integrate UI Design on waiting list page using old services.

CC : @chiefardi

**Comment by chiefardi** [comment]
Right on, thank you.

**Comment by Aries1711** [comment]
@chiefardi is already done with phase 1. The next features are in waiting status, so I'll focus on platform development (backend and frontend) for now.

**Comment by chiefardi** [comment]
Understood, great work.
